alchemy/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from rest_framework.routers import DefaultRouter

from . import views

app_name = 'alchemy'

# Create a router and register our viewsets with it.
router = DefaultRouter()
router.register(r'recipes', views.RecipesViewSet)
router.register(r'ingredients', views.IngredientsViewSet)
router.register(r'components', views.ComponentsViewSet)

urlpatterns = [
    url(r'^$', views.index, name='index'),

    # The API URLs are now determined automatically by the router.
    url('api/', include(router.urls)),

]

"""
    RECIPES
"""
urlpatterns += [
    url(r'^recipes/$', views.recipes_list, name='recipes_list'),

    url(r'^recipes/own/$', views.recipes_list_own, name='recipes_list_own'),

    url(r'^recipes/add/$', views.recipes_add, name='recipes_add'),

    url(r'^recipes/(?P<recipe_id>[0-9]+)/edit/info/$', views.recipes_edit_info, name='recipes_edit_info'),

    # Main recipe page
    url(r'^recipes/(?P<recipe_id>[0-9]+)/$', views.recipes_view, name='recipes_view'),

    # Edit recipe page
    url(r'^recipes/(?P<recipe_id>[0-9]+)/edit/$', views.recipes_edit, name='recipes_edit'),

    # Remove a recipe
    url(r'^recipes/(?P<recipe_id>[0-9]+)/remove/$', views.recipes_remove, name='recipes_remove'),

    # Vote recipe page
    url(r'^recipes/(?P<recipe_id>[0-9]+)/vote/$', views.recipes_vote, name='recipes_vote'),

]

"""
    RECIPES KINDS
"""
urlpatterns += [
    url(r'^recipes/kinds/$', views.recipes_kinds_index, name='recipes_kinds_list'),

    # Register new brand in database
    url(r'^recipes/kinds/add/$', views.recipes_kinds_add, name='recipes_kinds_add'),

    url(r'^recipes/kinds/edit/(?P<brand_id>[0-9]+)$', views.recipes_kinds_edit, name='recipes_kinds_edit')

]

"""
    COMPONENTS
"""
urlpatterns += [

    # View all components
    url(r'^components/$', views.components_index, name='components_list'),

    # Edit a component
    url(r'^components/(?P<component_id>[0-9]+)/edit/$', views.components_edit, name='components_edit'),

    # Remove a component
    url(r'^components/(?P<component_id>[0-9]+)/remove/$', views.components_remove, name='components_remove'),

]

"""
    COMPONENTS KINDS
"""
urlpatterns += [
    url(r'^components/kinds/$', views.components_kinds_index, name='components_kinds_list'),

    # Register new brand in database
    url(r'^components/kinds/add/$', views.components_kinds_add, name='components_kinds_add'),

    url(r'^components/kinds/edit/(?P<brand_id>[0-9]+)$', views.components_kinds_edit, name='components_kinds_edit')

]

"""
    BRANDS
"""
urlpatterns += [
    url(r'^brands/$', views.brands_index, name='brands_list'),

    # Register new brand in database
    url(r'^brands/add/$', views.brands_add, name='brands_add'),

    url(r'^brands/edit/(?P<brand_id>[0-9]+)$', views.brands_edit, name='brands_edit'),

    url(r'^brands/remove/(?P<brand_id>[0-9]+)$', views.brands_remove, name='brands_remove')

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

vape_manager/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic.base import TemplateView
from django.views.i18n import JavaScriptCatalog
from rest_framework import routers

from . import views

router = routers.DefaultRouter()
router.register(r'users', views.UserViewSet)
router.register(r'groups', views.GroupViewSet)

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^ratings/', include('star_ratings.urls', namespace='ratings', app_name='ratings')),
    url(r'^comments/', include('django_comments_xtd.urls')),
    url(r'^', include('accounts.urls')),
    url(r'^', include('user_profile.urls')),
    url(r'^api/', include(router.urls)),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^alchemy/', include('alchemy.urls')),
    url(r'^contact/', views.contact_us, name='contact'),
    url('', TemplateView.as_view(template_name='home.html'), name='home'),
    url(r'jsi18n/', JavaScriptCatalog.as_view(), name='javascript-catalog'),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

alchemy/forms/BrandForm.py
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit
from django import forms
from django.core.exceptions import NON_FIELD_ERRORS
from django.utils.translation import gettext_lazy as _

from alchemy.models import Brand


class BrandForm(forms.ModelForm):
    class Meta:
        model = Brand
        # exclude = ["author"]
        fields = ('name', 'url')
        labels = {
            'title': _('Nombre'),
        }
        help_texts = {
            'title': _('Especifica el nombre de la marca.'),
        }
        error_messages = {
            'title': {
                'max_length': _("El nombre de la marca es demasiado largo."),
            },

            # Overwrite default messages
            NON_FIELD_ERRORS: {
                'unique_together': "%(model_name)s's %(field_labels)s are not unique.",
            }
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_method = 'post'
        self.helper.add_input(Submit('submit', 'Save brand'))

    def clean_name(self):
        # custom validation for the name field
        return self.cleaned_data['name']

alchemy/forms/ComponentForm.py
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit
from django import forms
from django.core.exceptions import NON_FIELD_ERRORS
from django.utils.translation import gettext_lazy as _

from alchemy.models import Component, Brand, ComponentKind
from .ReletedFieldWiggetCanAdd import RelatedFieldWidgetCanAdd


class ComponentForm(forms.ModelForm):
    class Meta:
        model = Component
        fields = ('name', 'description', "brand", "kind")
        labels = {
            'name': _('Name'),
        }
        help_texts = {
            'name': _('Name of the component.'),
        }
        error_messages = {
            # Overwrite default messages
            NON_FIELD_ERRORS: {
                'unique_together': "%(model_name)s's %(field_labels)s are not unique."
            }
        }

        widgets = {
            'description': forms.Textarea(attrs={'cols': 20, 'rows': 5}),
            'brand': RelatedFieldWidgetCanAdd(Brand, related_url="alchemy:brands_add", origin_url=None,
                                              attrs={'class': 'form-control'}),
            'kind': RelatedFieldWidgetCanAdd(ComponentKind, related_url="alchemy:components_kinds_add", origin_url=None,
                                             attrs={'class': 'form-control'})

        }

    def __init__(self, origin_url=None, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields["brand"].widget.origin_url = origin_url
        self.fields["kind"].widget.origin_url = origin_url

        self.helper = FormHelper()
        self.helper.form_method = 'post'
        self.helper.add_input(Submit('submit_component', 'Register component'))

alchemy/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, render, redirect

from . import forms
from . import models


def components_form_action(request):
    """

    :param request:
    :return: form.ComponentForm, Bool
    """
    # if this is a POST request we need to process the form data
    if request.method == 'POST' and "submit_component" in request.POST:
        # create a form instance and populate it with data from the request:
        form = forms.ComponentForm(data=request.POST, origin_url=request.get_full_path())
        # check whether it's valid:
        if form.is_valid():
            # process the data in form.cleaned_data as required
            recipe = form.save(commit=False)
            recipe.author = request.user
            recipe.save()

            # redirect to the edit page
            return form, True


    # if a GET (or any other method) we'll create a blank form
    else:
        form = forms.ComponentForm(origin_url=request.get_full_path())

    return form, False


def ingredients_form_action(request, recipe):
    # if this is a POST request we need to process the form data
    # ReciFormSet = modelformset_factory(Recipe, form=RecipeForm)
    if request.method == 'POST' and "submit_ingredient" in request.POST:
        # create a form instance and populate it with data from the request:
        form = forms.IngredientForm(data=request.POST, origin_url=request.get_full_path())
        # check whether it's valid:
        if form.is_valid():
            # process the data in form.cleaned_data as required
            ingredient = form.save(commit=False)
            ingredient.author = request.user
            ingredient.recipe = recipe
            ingredient.save()

            return form, True

    # if a GET (or any other method) we'll create a blank form
    else:
        form = forms.IngredientForm(origin_url=request.get_full_path())

    return form, False


@login_required
def index(request):
    recipes = models.Recipe.objects.filter(is_public=True).order_by('-pub_date')[:5]
    context = {'recipes_list': recipes}
    return render(request, 'index.html', context)


"""
    Recipes views
"""


@login_required
def recipes_list(request):
    recipes = models.Recipe.objects.filter(is_public=True).order_by('-pub_date')
    context = {'recipes_list': recipes}
    return render(request, 'recipes/list_public.html', context)


@login_required
def recipes_list_own(request):
    recipes = models.Recipe.objects.filter(author=request.user).order_by('-pub_date')
    context = {'recipes_list': recipes}
    return render(request, 'recipes/list.html', context)


@login_required
def recipes_add(request):
    # if this is a POST request we need to process the form data
    # ReciFormSet = modelformset_factory(Recipe, form=RecipeForm)
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        print(request.user)
        form = forms.RecipeForm(request.POST)
        # check whether it's valid:
        if form.is_valid():
            # process the data in form.cleaned_data as required
            recipe = form.save(commit=False)
            recipe.author = request.user
            recipe.save()

            # redirect to the edit page
            return redirect('alchemy:recipes_edit', recipe_id=recipe.id)

    # if a GET (or any other method) we'll create a blank form
    else:
        form = forms.RecipeForm()
    return render(request, 'recipes/add.html', {'form': form})


@login_required
def recipes_edit_info(request, recipe_id):
    recipe = get_object_or_404(models.Recipe, pk=recipe_id)
    # if this is a POST request we need to process the form data
    # ReciFormSet = modelformset_factory(Recipe, form=RecipeForm)
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        print(request.user)
        form = forms.RecipeForm(request.POST, instance=recipe)
        # check whether it's valid:
        if form.is_valid():
            # process the data in form.cleaned_data as required
            recipe = form.save(commit=False)
            recipe.author = request.user
            recipe.save()

            # redirect to the edit page
            return redirect('alchemy:recipes_edit', recipe_id=recipe.id)

    # if a GET (or any other method) we'll create a blank form
    else:
        form = forms.RecipeForm(instance=recipe)
    return render(request, 'recipes/edit_info.html', {'form': form})


@login_required
def recipes_view(request, recipe_id):
    recipe = get_object_or_404(models.Recipe, pk=recipe_id)
    ingredients = models.Ingredient.objects.filter(recipe=recipe)
    return render(request, 'recipes/watch.html', {'recipe': recipe,
                                                  "ingredients": ingredients})


@login_required
def recipes_edit(request, recipe_id):
    recipe = get_object_or_404(models.Recipe, pk=recipe_id)

    components_form, res1 = components_form_action(request)
    ingredient_form, res2 = ingredients_form_action(request, recipe)

    if res1 or res2:
        if request.GET.get('form_origin'):
            url_redirect = request.GET.get('form_origin')
            return redirect(url_redirect)
        else:
            url_redirect = request.GET.get('next') if request.GET.get(
                'next') is not None else 'alchemy:recipes_edit'

            return redirect(url_redirect, recipe_id=recipe.id)

    ingredients = models.Ingredient.objects.filter(recipe=recipe)
    return render(request, 'recipes/edit.html',
                  {'recipe': recipe,
                   'component_form': components_form,
                   "ingredients_list": ingredients,
                   'ingredient_form': ingredient_form
                   })


@login_required
def recipes_remove(request, recipe_id):
    recipe = get_object_or_404(models.Recipe, pk=recipe_id)

    recipe.delete()

    return redirect('alchemy:recipes_list')


@login_required
def recipes_vote(request, recipe_id):
    recipe = get_object_or_404(models.Recipe, pk=recipe_id)
    # TODO:


"""
    Recipes kinds views
"""


def recipes_kinds_index(request):
    brands = models.RecipeKind.objects.order_by('-name')[:5]
    context = {'kinds': brands}
    return render(request, 'recipes/kinds_list.html', context)


@login_required
def recipes_kinds_add(request):
    # if this is a POST request we need to process the form data
    # ReciFormSet = modelformset_factory(Recipe, form=RecipeForm)
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        print(request.user)
        form = forms.RecipeKindForm(request.POST)
        # check whether it's valid:
        if form.is_valid():
            # process the data in form.cleaned_data as required
            recipe_kind = form.save(commit=False)
            recipe_kind.author = request.user
            recipe_kind.save()

            # redirect to the edit page
            return redirect('alchemy:recipes_kinds_list')

    # if a GET (or any other method) we'll create a blank form
    else:
        form = forms.RecipeKindForm()
    return render(request, 'recipes/kinds_add.html', {'form': form})


@login_required
def recipes_kinds_edit(request, brand_id):
    brand = get_object_or_404(models.RecipeKind, pk=brand_id)


"""
    Components views
"""


@login_required
def components_index(request):
    components = models.Component.objects.order_by('-name')

    components_form, res1 = components_form_action(request)

    if res1:
        return redirect(request.get_full_path())

    context = {'components_list': components,
               'component_form': components_form}

    return render(request, 'components/index.html', context)


@login_required
def components_edit(request, component_id):
    component = get_object_or_404(models.Component, pk=component_id)

    # if this is a POST request we need to process the form data
    # ReciFormSet = modelformset_factory(Recipe, form=RecipeForm)
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        print(request.user)
        form = forms.ComponentForm(data=request.POST, instance=component, origin_url=request.get_full_path())
        # check whether it's valid:
        if form.is_valid():
            # process the data in form.cleaned_data as required
            # component = form.save(commit=False)
            # component.author = request.user
            component.save()

            # redirect to the edit page
            return redirect('alchemy:components_list')

    # if a GET (or any other method) we'll create a blank form
    else:
        form = forms.ComponentForm(instance=component, origin_url=request.get_full_path())

    return render(request, 'components/edit.html',
                  {
                      'component': component,
                      'component_form': form
                  })


@login_required
def components_remove(request, component_id):
    recipe = get_object_or_404(models.Component, pk=component_id)

    recipe.delete()

    return redirect('alchemy:components_list')


"""
    Recipes kinds views
"""


def components_kinds_index(request):
    brands = models.RecipeKind.objects.order_by('-name')[:5]
    context = {'kinds': brands}
    return render(request, 'components/kinds_list.html', context)


@login_required
def components_kinds_add(request):
    # if this is a POST request we need to process the form data
    # ReciFormSet = modelformset_factory(Recipe, form=RecipeForm)
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        print(request.user)
        form = forms.ComponentKindForm(request.POST)
        # check whether it's valid:
        if form.is_valid():
            # process the data in form.cleaned_data as required

alchemy/templates/base_alchemy.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <title>{% block head_title %}{% endblock %}</title>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">


    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet"
          id="bootstrap-css">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
          integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.2.0/css/all.css"
          integrity="sha384-hWVjflwFxL6sNzntih27bfxkr27PmbbK/iSvJ+a4+0owXq79v+lsFkW54bOGbiDQ" crossorigin="anonymous">

    <link rel="stylesheet" href="{% static 'css/sidebar.css' %}">
    <link rel="stylesheet" href="{% static 'css/sidebar-themes.css' %}">
    <link rel="shortcut icon" type="image/png" href="img/favicon.png"/>

    <link rel="stylesheet" href="{% static 'star-ratings/css/star-ratings.css' %}">

</head>
<body>


<div class="page-wrapper default-theme sidebar-bg bg1 toggled">
    {% include 'sidebar.html' %}
    {% block content_header %}{% endblock %}
    <main class="page-content">
        {% include 'navbar.html' %}
        <div class="container-fluid">

            <div class="row justify-content-center">
                <div class="col-12">
                    <h1 class="mt-2">{% block page_title %}{% endblock %}</h1>
                    <hr class="mt-0 mb-4">
                    {% block content %}{% endblock %}
                </div>
            </div>
        </div>
    </main>
</div>

{% block content_footer %}{% endblock %}

<!-- using online scripts -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
        integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
        integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
        crossorigin="anonymous"></script>

<script src="//malihu.github.io/custom-scrollbar/jquery.mCustomScrollbar.concat.min.js"></script>
<script src="{% static 'js/sidebar.js' %}"></script>

<script type="text/javascript"
        src="https://cdn.datatables.net/v/bs4/dt-1.10.18/b-1.5.6/r-2.2.2/sc-2.0.0/datatables.min.js"></script>
<script src="{% static 'js/main.js' %}"></script>

<script type="text/javascript" src="{% static 'star-ratings/js/dist/star-ratings.min.js' %}"></script>

<!-- vue.js files -->
<script src="https://cdn.jsdelivr.net/npm/vue"></script>
<script src="https://unpkg.com/axios/dist/axios.min.js"></script>
<script src="{% static 'js/alchemy.js' %}"></script>

{% block extra_js %}{% endblock %}

<!-- using local scripts -->
<!-- <script src="../node_modules/jquery/dist/jquery.min.js"></script>
<script src="../node_modules/popper.js/dist/umd/popper.min.js"></script>
<script src="../node_modules/bootstrap/dist/js/bootstrap.min.js"></script>
<script src="../node_modules/malihu-custom-scrollbar-plugin/jquery.mCustomScrollbar.concat.min.js"></script> -->

</body>
</html>

alchemy/templates/index.html
<!-- templates/signup.html -->
{% extends 'base_alchemy.html' %}

{% block title %}Alchemy - main{% endblock %}
{% block page_title %}Alchemy{% endblock %}
{% block content %}
    <div class="card-deck">
        <div class="card mb-3" style="width: 18rem;">
            <div class="card-header bg-success text-white">Recipes</div>
            <div class="card-body">
                <p class="card-text">Some quick example text to build on the card title and make up the bulk of the
                    card's content.</p>
                <a href="{% url 'alchemy:recipes_list' %}" class="btn btn-success">Recipes list</a>
            </div>
        </div>
        <div class="card mb-3" style="width: 18rem;">
            <div class="card-header bg-warning text-white">Brands</div>
            <div class="card-body">
                <p class="card-text">Some quick example text to build on the card title and make up the bulk of the
                    card's content.</p>
                <a href="{% url 'alchemy:brands_list' %}" class="btn btn-warning">Brands list</a>
            </div>
        </div>
        <div class="card mb-3" style="width: 18rem;">
            <div class="card-header bg-secondary text-white">Components</div>
            <div class="card-body">
                <p class="card-text">Some quick example text to build on the card title and make up the bulk of the
                    card's content.</p>
                <a href="{% url 'alchemy:components_list' %}" class="btn btn-secondary">Components list</a>
            </div>
        </div>
    </div>
    <h2>Last added recipes</h2>
    <table id="table-recipes-public" class="table table-striped table-bordered"
           data-link-add="{% url 'alchemy:recipes_add' %}" style="width:100%">
        <thead>
        <tr>
            <th>Title</th>
            <th>Description</th>
            <th>Kind</th>
            <th>Pub. date</th>
            <th>Author</th>
            <th>Rate</th>
            <th>View</th>
        </tr>
        </thead>
        <tbody>
        {% if recipes_list %}
            {% for recipe in recipes_list %}
                <tr>
                    <td>{{ recipe.title }}</td>
                    <td>{{ recipe.description }}</td>
                    <td>{{ recipe.kind }}</td>
                    <td>{{ recipe.pub_date }}</td>
                    <td>{{ recipe.author }}</td>
                    <td>{{ recipe.ratings.get.average }}</td>
                    <td><a class="btn btn-info" href="{% url 'alchemy:recipes_view' recipe.id %}"><i
                            class="fas fa-prescription-bottle-alt"></i></a></td>
                </tr>
            {% endfor %}
        {% endif %}
        </tbody>
    </table>

{% endblock %}