alchemy/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from rest_framework.routers import DefaultRouter

from . import views

app_name = 'alchemy'

# Create a router and register our viewsets with it.
router = DefaultRouter()
router.register(r'recipes', views.RecipesViewSet)
router.register(r'ingredients', views.IngredientsViewSet)
router.register(r'components', views.ComponentsViewSet)

urlpatterns = [
    url(r'^$', views.index, name='index'),

    # The API URLs are now determined automatically by the router.
    url('api/', include(router.urls)),

]

"""
    RECIPES
"""
urlpatterns += [
    url(r'^recipes/$', views.recipes_list, name='recipes_list'),

    url(r'^recipes/own/$', views.recipes_list_own, name='recipes_list_own'),

    url(r'^recipes/add/$', views.recipes_add, name='recipes_add'),

    url(r'^recipes/(?P<recipe_id>[0-9]+)/edit/info/$', views.recipes_edit_info, name='recipes_edit_info'),

    # Main recipe page
    url(r'^recipes/(?P<recipe_id>[0-9]+)/$', views.recipes_view, name='recipes_view'),

    # Edit recipe page
    url(r'^recipes/(?P<recipe_id>[0-9]+)/edit/$', views.recipes_edit, name='recipes_edit'),

    # Remove a recipe
    url(r'^recipes/(?P<recipe_id>[0-9]+)/remove/$', views.recipes_remove, name='recipes_remove'),

    # Vote recipe page
    url(r'^recipes/(?P<recipe_id>[0-9]+)/vote/$', views.recipes_vote, name='recipes_vote'),

]

"""
    RECIPES KINDS
"""
urlpatterns += [
    url(r'^recipes/kinds/$', views.recipes_kinds_index, name='recipes_kinds_list'),

    # Register new brand in database
    url(r'^recipes/kinds/add/$', views.recipes_kinds_add, name='recipes_kinds_add'),

    url(r'^recipes/kinds/edit/(?P<brand_id>[0-9]+)$', views.recipes_kinds_edit, name='recipes_kinds_edit')

]

"""
    COMPONENTS
"""
urlpatterns += [

    # View all components
    url(r'^components/$', views.components_index, name='components_list'),

    # Edit a component
    url(r'^components/(?P<component_id>[0-9]+)/edit/$', views.components_edit, name='components_edit'),

    # Remove a component
    url(r'^components/(?P<component_id>[0-9]+)/remove/$', views.components_remove, name='components_remove'),

]

"""
    COMPONENTS KINDS
"""
urlpatterns += [
    url(r'^components/kinds/$', views.components_kinds_index, name='components_kinds_list'),

    # Register new brand in database
    url(r'^components/kinds/add/$', views.components_kinds_add, name='components_kinds_add'),

    url(r'^components/kinds/edit/(?P<brand_id>[0-9]+)$', views.components_kinds_edit, name='components_kinds_edit')

]

"""
    BRANDS
"""
urlpatterns += [
    url(r'^brands/$', views.brands_index, name='brands_list'),

    # Register new brand in database
    url(r'^brands/add/$', views.brands_add, name='brands_add'),

    url(r'^brands/edit/(?P<brand_id>[0-9]+)$', views.brands_edit, name='brands_edit'),

    url(r'^brands/remove/(?P<brand_id>[0-9]+)$', views.brands_remove, name='brands_remove')

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

vape_manager/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic.base import TemplateView
from django.views.i18n import JavaScriptCatalog
from rest_framework import routers

from . import views

router = routers.DefaultRouter()
router.register(r'users', views.UserViewSet)
router.register(r'groups', views.GroupViewSet)

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^ratings/', include('star_ratings.urls', namespace='ratings', app_name='ratings')),
    url(r'^comments/', include('django_comments_xtd.urls')),
    url(r'^', include('accounts.urls')),
    url(r'^', include('user_profile.urls')),
    url(r'^api/', include(router.urls)),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^alchemy/', include('alchemy.urls')),
    url(r'^contact/', views.contact_us, name='contact'),
    url('', TemplateView.as_view(template_name='home.html'), name='home'),
    url(r'jsi18n/', JavaScriptCatalog.as_view(), name='javascript-catalog'),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

alchemy/models.py
from django.contrib.auth.models import User
from django.contrib.contenttypes.fields import GenericRelation
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models
from django.urls import reverse
from django.utils.safestring import mark_safe
from star_ratings.models import Rating


class RecipeKind(models.Model):
    name = models.CharField(max_length=200)
    description = models.fields.TextField(default='')
    author = models.ForeignKey(User, on_delete=models.PROTECT)

    def __str__(self):
        return self.name + " - " + self.description


class Recipe(models.Model):
    title = models.CharField(max_length=200)
    description = models.fields.TextField(default='')
    pub_date = models.DateTimeField('date published', auto_now_add=True)
    kind = models.ForeignKey(RecipeKind, on_delete=models.PROTECT, default=None, null=True)
    author = models.ForeignKey(User, on_delete=models.PROTECT)
    ratings = GenericRelation(Rating, related_query_name='recipe_ratings')
    is_public = models.BooleanField(default=False)

    def is_public_icon(self):
        if self.is_public:
            output = '<i class="fas fa-check" style="font-size: 2em; color: Green;"></i>'
        else:
            output = '<i class="fas fa-times" style="font-size: 2em; color: Red;"></i>'

        return mark_safe(output)

    def get_ingredients(self):
        return Ingredient.objects.filter(recipe=self)

    def get_absolute_url(self):
        return reverse('alchemy:recipes_edit', kwargs={"recipe_id": self.id})

    def get_view_url(self):
        return reverse('alchemy:recipes_view', kwargs={"recipe_id": self.id})

    def get_average_ratings(self):
        if self.ratings.count() > 0:
            return self.ratings.get().average
        else:
            return 0.0

    def __str__(self):
        return self.title


class Brand(models.Model):
    name = models.CharField(max_length=200)
    url = models.CharField(max_length=200)

    def __str__(self):
        return self.name


class ComponentKind(models.Model):
    name = models.CharField(max_length=200)
    description = models.fields.TextField()

    def __str__(self):
        return self.name


class Component(models.Model):
    name = models.CharField(max_length=200)
    description = models.fields.TextField()
    author = models.ForeignKey(User, on_delete=models.PROTECT)
    brand = models.ForeignKey(Brand, on_delete=models.PROTECT, default=None, null=True)
    kind = models.ForeignKey(ComponentKind, on_delete=models.PROTECT, default=None, null=True)

    def __str__(self):
        return self.name + " - " + str(self.brand)


class Ingredient(models.Model):
    recipe = models.ForeignKey(Recipe, related_name='ingredients', on_delete=models.CASCADE)
    component = models.ForeignKey(Component, on_delete=models.PROTECT)
    percentage = models.FloatField()

    def __str__(self):
        return str(self.component) + " - " + str(self.percentage) + "%"


class RecipeValoration(models.Model):
    recipe = models.ForeignKey(Recipe, on_delete=models.CASCADE)
    value = models.PositiveIntegerField(default=10, validators=[MinValueValidator(0), MaxValueValidator(10)])
    comment = models.fields.TextField(default='')

alchemy/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, render, redirect

from . import forms
from . import models


def components_form_action(request):
    """

    :param request:
    :return: form.ComponentForm, Bool
    """
    # if this is a POST request we need to process the form data
    if request.method == 'POST' and "submit_component" in request.POST:
        # create a form instance and populate it with data from the request:
        form = forms.ComponentForm(data=request.POST, origin_url=request.get_full_path())
        # check whether it's valid:
        if form.is_valid():
            # process the data in form.cleaned_data as required
            recipe = form.save(commit=False)
            recipe.author = request.user
            recipe.save()

            # redirect to the edit page
            return form, True


    # if a GET (or any other method) we'll create a blank form
    else:
        form = forms.ComponentForm(origin_url=request.get_full_path())

    return form, False


def ingredients_form_action(request, recipe):
    # if this is a POST request we need to process the form data
    # ReciFormSet = modelformset_factory(Recipe, form=RecipeForm)
    if request.method == 'POST' and "submit_ingredient" in request.POST:
        # create a form instance and populate it with data from the request:
        form = forms.IngredientForm(data=request.POST, origin_url=request.get_full_path())
        # check whether it's valid:
        if form.is_valid():
            # process the data in form.cleaned_data as required
            ingredient = form.save(commit=False)
            ingredient.author = request.user
            ingredient.recipe = recipe
            ingredient.save()

            return form, True

    # if a GET (or any other method) we'll create a blank form
    else:
        form = forms.IngredientForm(origin_url=request.get_full_path())

    return form, False


@login_required
def index(request):
    recipes = models.Recipe.objects.filter(is_public=True).order_by('-pub_date')[:5]
    context = {'recipes_list': recipes}
    return render(request, 'index.html', context)


"""
    Recipes views
"""


@login_required
def recipes_list(request):
    recipes = models.Recipe.objects.filter(is_public=True).order_by('-pub_date')
    context = {'recipes_list': recipes}
    return render(request, 'recipes/list_public.html', context)


@login_required
def recipes_list_own(request):
    recipes = models.Recipe.objects.filter(author=request.user).order_by('-pub_date')
    context = {'recipes_list': recipes}
    return render(request, 'recipes/list.html', context)


@login_required
def recipes_add(request):
    # if this is a POST request we need to process the form data
    # ReciFormSet = modelformset_factory(Recipe, form=RecipeForm)
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        print(request.user)
        form = forms.RecipeForm(request.POST)
        # check whether it's valid:
        if form.is_valid():
            # process the data in form.cleaned_data as required
            recipe = form.save(commit=False)
            recipe.author = request.user
            recipe.save()

            # redirect to the edit page
            return redirect('alchemy:recipes_edit', recipe_id=recipe.id)

    # if a GET (or any other method) we'll create a blank form
    else:
        form = forms.RecipeForm()
    return render(request, 'recipes/add.html', {'form': form})


@login_required
def recipes_edit_info(request, recipe_id):
    recipe = get_object_or_404(models.Recipe, pk=recipe_id)
    # if this is a POST request we need to process the form data
    # ReciFormSet = modelformset_factory(Recipe, form=RecipeForm)
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        print(request.user)
        form = forms.RecipeForm(request.POST, instance=recipe)
        # check whether it's valid:
        if form.is_valid():
            # process the data in form.cleaned_data as required
            recipe = form.save(commit=False)
            recipe.author = request.user
            recipe.save()

            # redirect to the edit page
            return redirect('alchemy:recipes_edit', recipe_id=recipe.id)

    # if a GET (or any other method) we'll create a blank form
    else:
        form = forms.RecipeForm(instance=recipe)
    return render(request, 'recipes/edit_info.html', {'form': form})


@login_required
def recipes_view(request, recipe_id):
    recipe = get_object_or_404(models.Recipe, pk=recipe_id)
    ingredients = models.Ingredient.objects.filter(recipe=recipe)
    return render(request, 'recipes/watch.html', {'recipe': recipe,
                                                  "ingredients": ingredients})


@login_required
def recipes_edit(request, recipe_id):
    recipe = get_object_or_404(models.Recipe, pk=recipe_id)

    components_form, res1 = components_form_action(request)
    ingredient_form, res2 = ingredients_form_action(request, recipe)

    if res1 or res2:
        if request.GET.get('form_origin'):
            url_redirect = request.GET.get('form_origin')
            return redirect(url_redirect)
        else:
            url_redirect = request.GET.get('next') if request.GET.get(
                'next') is not None else 'alchemy:recipes_edit'

            return redirect(url_redirect, recipe_id=recipe.id)

    ingredients = models.Ingredient.objects.filter(recipe=recipe)
    return render(request, 'recipes/edit.html',
                  {'recipe': recipe,
                   'component_form': components_form,
                   "ingredients_list": ingredients,
                   'ingredient_form': ingredient_form
                   })


@login_required
def recipes_remove(request, recipe_id):
    recipe = get_object_or_404(models.Recipe, pk=recipe_id)

    recipe.delete()

    return redirect('alchemy:recipes_list')


@login_required
def recipes_vote(request, recipe_id):
    recipe = get_object_or_404(models.Recipe, pk=recipe_id)
    # TODO:


"""
    Recipes kinds views
"""


def recipes_kinds_index(request):
    brands = models.RecipeKind.objects.order_by('-name')[:5]
    context = {'kinds': brands}
    return render(request, 'recipes/kinds_list.html', context)


@login_required
def recipes_kinds_add(request):
    # if this is a POST request we need to process the form data
    # ReciFormSet = modelformset_factory(Recipe, form=RecipeForm)
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        print(request.user)
        form = forms.RecipeKindForm(request.POST)
        # check whether it's valid:
        if form.is_valid():
            # process the data in form.cleaned_data as required
            recipe_kind = form.save(commit=False)
            recipe_kind.author = request.user
            recipe_kind.save()

            # redirect to the edit page
            return redirect('alchemy:recipes_kinds_list')

    # if a GET (or any other method) we'll create a blank form
    else:
        form = forms.RecipeKindForm()
    return render(request, 'recipes/kinds_add.html', {'form': form})


@login_required
def recipes_kinds_edit(request, brand_id):
    brand = get_object_or_404(models.RecipeKind, pk=brand_id)


"""
    Components views
"""


@login_required
def components_index(request):
    components = models.Component.objects.order_by('-name')

    components_form, res1 = components_form_action(request)

    if res1:
        return redirect(request.get_full_path())

    context = {'components_list': components,
               'component_form': components_form}

    return render(request, 'components/index.html', context)


@login_required
def components_edit(request, component_id):
    component = get_object_or_404(models.Component, pk=component_id)

    # if this is a POST request we need to process the form data
    # ReciFormSet = modelformset_factory(Recipe, form=RecipeForm)
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        print(request.user)
        form = forms.ComponentForm(data=request.POST, instance=component, origin_url=request.get_full_path())
        # check whether it's valid:
        if form.is_valid():
            # process the data in form.cleaned_data as required
            # component = form.save(commit=False)
            # component.author = request.user
            component.save()

            # redirect to the edit page
            return redirect('alchemy:components_list')

    # if a GET (or any other method) we'll create a blank form
    else:
        form = forms.ComponentForm(instance=component, origin_url=request.get_full_path())

    return render(request, 'components/edit.html',
                  {
                      'component': component,
                      'component_form': form
                  })


@login_required
def components_remove(request, component_id):
    recipe = get_object_or_404(models.Component, pk=component_id)

    recipe.delete()

    return redirect('alchemy:components_list')


"""
    Recipes kinds views
"""


def components_kinds_index(request):
    brands = models.RecipeKind.objects.order_by('-name')[:5]
    context = {'kinds': brands}
    return render(request, 'components/kinds_list.html', context)


@login_required
def components_kinds_add(request):
    # if this is a POST request we need to process the form data
    # ReciFormSet = modelformset_factory(Recipe, form=RecipeForm)
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        print(request.user)
        form = forms.ComponentKindForm(request.POST)
        # check whether it's valid:
        if form.is_valid():
            # process the data in form.cleaned_data as required

alchemy/templates/recipes/add.html
<!-- templates/signup.html -->
{% extends 'base_alchemy.html' %}

{% load crispy_forms_tags %}

{% block title %}Add a recipe{% endblock %}
{% block page_title %}Add a recipe{% endblock %}
{% block content %}
    <div class="row">
        <div class="col-md-6 offset-md-3">
            {% crispy form %}
        </div>
    </div>
{% endblock %}

alchemy/templates/recipes/edit.html
<!-- templates/signup.html -->
{% extends 'base_alchemy.html' %}

{% load static %}
{% load crispy_forms_tags %}
{% load ratings %}

{% load comments %}
{% load comments_xtd %}

{% block title %}Recipe edition{% endblock %}
{% block page_title %}Recipe edition{% endblock %}

{% block content %}


    {% include "components/modal_add.html" %}

    <div class="row">
        <div class="col-md-10 offset-md-2">
            <div class="card-columns">
                <div class="card">
                    <div class="card-body">
                        <h4 class="card-title">Recipe Information</h4>
                        <table class="table table-striped table-bordered table-sm table-recipe-info">
                            <tbody>
                            <tr>
                                <td>Name:</td>
                                <td>{{ recipe.title }}</td>
                            </tr>
                            <tr>
                                <td>Description:</td>
                                <td>{{ recipe.description }}</td>
                            </tr>
                            <tr>
                                <td>Kind:</td>
                                <td>{{ recipe.kind.name }}</td>
                            </tr>
                            <tr>
                                <td>Date:</td>
                                <td>{{ recipe.pub_date }}</td>
                            </tr>
                            <tr>
                                <td>Author:</td>
                                <td>{{ recipe.author }}</td>
                            </tr>
                            <tr>
                                <td>Public:</td>
                                <td>{{ recipe.is_public_icon }}</td>
                            </tr>
                            <tr>
                                <td>Rate:</td>
                                <td>{{ recipe.ratings.get.average }}</td>
                            </tr>
                            </tbody>
                        </table>
                        <a href="{% url 'alchemy:recipes_edit_info' recipe.id %}?next={{ request.path|urlencode }}"
                           class="btn btn-warning btn-block">Edit Recipe info</a>
                    </div>
                </div>
                <div class="card">
                    <div class="card-body">
                        <h4 class="card-title">Recipe Valoration</h4>
                        {% ratings recipe %}
                    </div>
                </div>

            </div>
        </div>
    </div>

    <div class="row ingredients" id="recipe-edition">

        {% include 'recipes/modal_ingredient.html' %}
        <div class="col-md-8 offset-md-2">
            <div class="card mb-3">
                <div class="card-body">
                    <h4 class="card-title">Ingredients list</h4>
                    <div id="div_id_title" class="form-group row">
                        <label for="id_title" class="col-form-label col-1">
                            Quantity in ml<span class="asteriskField">*</span>
                        </label>
                        <div class="col-2">
                            <input type="number" name="title" maxlength="200" class="textinput textInput form-control"
                                   required="" id="id_title" v-model="qtt">
                            <small id="hint_id_title" class="form-text text-muted">Quantity of liquid to produce (ml).
                            </small>
                        </div>
                        <div class="btn-group btn-group-toggle col-2" style="height: max-content">
                            <label class="btn btn-primary" :class="{ 'active': metric == '%' }">
                                <input type="radio" name="options" value="%"
                                       v-model="metric"> %
                            </label>
                            <label class="btn btn-primary" :class="{ 'active': metric == 'ml' }">
                                <input type="radio" name="options" value="ml"
                                       v-model="metric"> ml
                            </label>
                        </div>
                    </div>

                    <h4>Recipe to produce ${ qtt } ml of liquid</h4>
                    <ul>
                        <li v-for="msg in recipe.messages.error"> ${ msg }</li>
                    </ul>

                    <form v-on:submit.prevent="addIngredient()" method="post">
                        {% csrf_token %}
                        <table class="table table-striped table-bordered table-sm">
                            <thead>
                            <tr>
                                <th>Component</th>
                                <th>Percentage</th>
                                <th>Quantity (ml)</th>
                                <th>Action</th>
                            </tr>
                            </thead>
                            <tbody>
                            <tr v-for="ingredient in recipe.ingredients">
                                <td>${ingredient.component.name}</td>
                                <td>${ingredient.percentage}</td>
                                <td>${ (ingredient.percentage/100)*qtt }</td>
                                <td>
                                    <a class="btn btn-link" v-on:click="setIngredient(ingredient)" data-toggle="modal"
                                       data-target="#modal-edit-ingredient">
                                        <i class="fas fa-edit"></i>
                                    </a>
                                    <a class="btn btn-link" v-on:click="deleteIngredient(ingredient.id)">
                                        <i class="fas fa-trash-alt"></i>
                                    </a>
                                </td>
                            </tr>
                            <tr>
                                <td class="w-50">
                                    <div class="input-group">
                                        <select name="component" id="id_component"
                                                class="form-control relatedfieldwidgetcanadd form-control"
                                                required="required" v-model="newIngredient.component_id">
                                            <option value="" selected="selected">---------</option>
                                            <option v-for="comp in components" v-bind:value=comp.id>
                                                ${comp.name} - ${comp.brand}
                                            </option>
                                        </select>
                                        <button id="add_id_component" type="button" data-toggle="modal"
                                                data-target="#modal-form-component" class="btn btn-success">
                                            <i class="fas fa-plus"></i>
                                        </button>
                                    </div>
                                </td>
                                <td class="w-20" v-if="metric == '%'">
                                    <input name="percentage" class="numberinput form-control" id="id_percentage"
                                           type="number" step="any" required="required"
                                           v-model="newIngredient.percentage">
                                </td>
                                <td class="w-20" v-else>
                                    <input name="percentage" id="id_percentage"
                                           type="hidden" step="any" required="required"
                                           v-model="newIngredient.percentage">
                                    ${ newIngredient.percentage }
                                </td>
                                <td class="w-20" v-if="metric == 'ml'">
                                    <input class="numberinput form-control"
                                           type="number" step="any" required="required"
                                           v-model="ml">

                                </td>
                                <td class="w-20" v-else>
                                    ${ (newIngredient.percentage/100)*qtt }
                                </td>
                                <td class="w-10">
                                    <button type="submit" name="submit_ingredient" class="btn btn-primary">Add
                                        ingredient
                                    </button>
                                </td>
                            </tr>
                            </tbody>
                        </table>
                    </form>
                </div>
            </div>
            <div class="card" id="recipe-comments">
                <div class="card-body">
                    <h4 class="card-title">Comments</h4>
                    {% get_comment_count for recipe as comment_count %}
                    <div class="card card-block mb-5">
                        <div class="card-body">
                            <h4 class="card-title text-center pb-3">Post your comment</h4>
                            {% if request.user.is_authenticated %}
                                {% render_comment_form for recipe %}
                            {% endif %}
                        </div>
                    </div>
                    {% if comment_count %}
                        <hr/>
                        <div class="comments">
                            {% render_xtdcomment_tree for recipe %}
                        </div>
                    {% endif %}

                </div>
            </div>
        </div>

        <div class="loading" v-if="loading===true">Loading&#8230;</div>
    </div>
{% endblock %}

{% block extra_js %}
    <script>
        axios.defaults.xsrfCookieName = "csrftoken";
        axios.defaults.xsrfHeaderName = "X-CSRFTOKEN";

        var recipe_id = {{ recipe.id }};
        var app = new Vue({
            el: '.ingredients',
            delimiters: ['${', '}'],
            data: {
                recipe: new Recipe(recipe_id),
                components: [],
                qtt: 50,
                metric: "%",
                loading: false,
                currentIngredient: {
                    id: null,
                    component_id: null,
                    percentage: null,
                    recipe_id: recipe_id
                },
                newIngredient: {
                    component_id: null,
                    percentage: null,
                    recipe_id: recipe_id
                },
            },
            mounted: function () {
                this.recipe.get();
                this.getComponents();
            },
            computed: {
                ml: {
                    get: function () {
                        return (this.newIngredient.percentage / 100) * this.qtt
                    },
                    set: function (ml) {
                        this.newIngredient.percentage = (ml * 100) / this.qtt;
                    }
                }
            },
            methods: {
                setIngredient: function (ingredient) {
                    this.currentIngredient.id = ingredient.id;
                    this.currentIngredient.component_id = ingredient.component.id;
                    this.currentIngredient.percentage = ingredient.percentage;
                },
                addIngredient: function () {
                    this.recipe.addIngredient(this.newIngredient);
                },
                updateIngredient: function () {
                    this.recipe.updateIngredient(this.currentIngredient.id, this.currentIngredient);
                },
                deleteIngredient: function (id) {
                    this.recipe.removeIngredient(id);
                },
                getComponents(page = 1) {
                    this.loading = true;
                    axios.get('alchemy/api/components/?page=' + page)
                        .then((response) => {
                            this.components = this.components.concat(response.data.results);
                            if (response.data.next != null) {
                                this.getComponents(page + 1);
                            }
                            this.loading = false;
                        })
                        .catch((err) => {
                            this.loading = false;
                            console.log(err);
                        })
                }
            }
        });
    </script>
{% endblock %}

alchemy/templates/recipes/kinds_add.html
<!-- templates/signup.html -->
{% extends 'base_alchemy.html' %}

{% load crispy_forms_tags %}

{% block title %}Add a recipe kind{% endblock %}
{% block page_title %}Add a recipe kind{% endblock %}

{% block content %}
    {% crispy form %}
{% endblock %}

alchemy/templates/recipes/kinds_list.html
<!-- templates/signup.html -->
{% extends 'base_alchemy.html' %}

{% block title %}Recipes kinds{% endblock %}
{% block page_title %}Recipes kinds{% endblock %}

{% block content %}
    <a href="{% url 'alchemy:recipes_kinds_add' %}">
        Add a new recipe kind
    </a>
    {% if kinds %}
        <ul>
            {% for brand in kinds %}
                <li>
                    <a href="{% url 'alchemy:recipes_kinds_edit' brand.id %}">
                        {{ brand.name }}
                    </a>
                </li>
            {% endfor %}
        </ul>
    {% else %}
        <p>No brands available.</p>
    {% endif %}
{% endblock %}