alchemy/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from rest_framework.routers import DefaultRouter

from . import views

app_name = 'alchemy'

# Create a router and register our viewsets with it.
router = DefaultRouter()
router.register(r'recipes', views.RecipesViewSet)
router.register(r'ingredients', views.IngredientsViewSet)
router.register(r'components', views.ComponentsViewSet)

urlpatterns = [
    url(r'^$', views.index, name='index'),

    # The API URLs are now determined automatically by the router.
    url('api/', include(router.urls)),

]

"""
    RECIPES
"""
urlpatterns += [
    url(r'^recipes/$', views.recipes_list, name='recipes_list'),

    url(r'^recipes/own/$', views.recipes_list_own, name='recipes_list_own'),

    url(r'^recipes/add/$', views.recipes_add, name='recipes_add'),

    url(r'^recipes/(?P<recipe_id>[0-9]+)/edit/info/$', views.recipes_edit_info, name='recipes_edit_info'),

    # Main recipe page
    url(r'^recipes/(?P<recipe_id>[0-9]+)/$', views.recipes_view, name='recipes_view'),

    # Edit recipe page
    url(r'^recipes/(?P<recipe_id>[0-9]+)/edit/$', views.recipes_edit, name='recipes_edit'),

    # Remove a recipe
    url(r'^recipes/(?P<recipe_id>[0-9]+)/remove/$', views.recipes_remove, name='recipes_remove'),

    # Vote recipe page
    url(r'^recipes/(?P<recipe_id>[0-9]+)/vote/$', views.recipes_vote, name='recipes_vote'),

]

"""
    RECIPES KINDS
"""
urlpatterns += [
    url(r'^recipes/kinds/$', views.recipes_kinds_index, name='recipes_kinds_list'),

    # Register new brand in database
    url(r'^recipes/kinds/add/$', views.recipes_kinds_add, name='recipes_kinds_add'),

    url(r'^recipes/kinds/edit/(?P<brand_id>[0-9]+)$', views.recipes_kinds_edit, name='recipes_kinds_edit')

]

"""
    COMPONENTS
"""
urlpatterns += [

    # View all components
    url(r'^components/$', views.components_index, name='components_list'),

    # Edit a component
    url(r'^components/(?P<component_id>[0-9]+)/edit/$', views.components_edit, name='components_edit'),

    # Remove a component
    url(r'^components/(?P<component_id>[0-9]+)/remove/$', views.components_remove, name='components_remove'),

]

"""
    COMPONENTS KINDS
"""
urlpatterns += [
    url(r'^components/kinds/$', views.components_kinds_index, name='components_kinds_list'),

    # Register new brand in database
    url(r'^components/kinds/add/$', views.components_kinds_add, name='components_kinds_add'),

    url(r'^components/kinds/edit/(?P<brand_id>[0-9]+)$', views.components_kinds_edit, name='components_kinds_edit')

]

"""
    BRANDS
"""
urlpatterns += [
    url(r'^brands/$', views.brands_index, name='brands_list'),

    # Register new brand in database
    url(r'^brands/add/$', views.brands_add, name='brands_add'),

    url(r'^brands/edit/(?P<brand_id>[0-9]+)$', views.brands_edit, name='brands_edit'),

    url(r'^brands/remove/(?P<brand_id>[0-9]+)$', views.brands_remove, name='brands_remove')

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

vape_manager/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic.base import TemplateView
from django.views.i18n import JavaScriptCatalog
from rest_framework import routers

from . import views

router = routers.DefaultRouter()
router.register(r'users', views.UserViewSet)
router.register(r'groups', views.GroupViewSet)

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^ratings/', include('star_ratings.urls', namespace='ratings', app_name='ratings')),
    url(r'^comments/', include('django_comments_xtd.urls')),
    url(r'^', include('accounts.urls')),
    url(r'^', include('user_profile.urls')),
    url(r'^api/', include(router.urls)),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^alchemy/', include('alchemy.urls')),
    url(r'^contact/', views.contact_us, name='contact'),
    url('', TemplateView.as_view(template_name='home.html'), name='home'),
    url(r'jsi18n/', JavaScriptCatalog.as_view(), name='javascript-catalog'),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <title>{% block head_title %}{% endblock %}</title>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet"
          id="bootstrap-css">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
          integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.2.0/css/all.css"
          integrity="sha384-hWVjflwFxL6sNzntih27bfxkr27PmbbK/iSvJ+a4+0owXq79v+lsFkW54bOGbiDQ" crossorigin="anonymous">

    <!------ Include the above in your HEAD tag ---------->

</head>
<body>

{% include 'navbar.html' %}
<div class="page-wrapper">
    {% block content_header %}{% endblock %}
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-8">
                <h1 class="mt-2">{% block page_title %}{% endblock %}</h1>
                <hr class="mt-0 mb-4">
                {% block content %}
                {% endblock %}
            </div>
        </div>
    </div>
</div>

{% include 'footer.html' %}

{% block extra_js %}{% endblock %}

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
        integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
        integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
        crossorigin="anonymous"></script>

</body>
</html>

templates/contact.html
<!-- templates/signup.html -->
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block title %}Contact us{% endblock %}
{% block page_title %}Contact us{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-md-12">
            <p class="lead">
                Got a question? We'd love to hear from you.
                Send us a message and we'll respond as soon as possible.
            </p>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">

            {% crispy form %}
        </div>
    </div>
{% endblock %}

templates/footer.html
<!--footer starts from here-->
<footer class="footer">
    <div class="container bottom_border">
        <div class="row">
            <div class=" col-sm-4 col-md col-sm-4  col-12 col">
                <h5 class="headin5_amrc col_white_amrc pt2">Find us</h5>
                <!--headin5_amrc-->
                <p class="mb10">
                    Vape Manager is a non-profit organization without a specific location. You can contact us by e-mail.
                </p>
                {#                <p><i class="fa fa-location-arrow"></i> 9878/25 sec 9 rohini 35 </p>#}
                {#                <p><i class="fa fa-phone"></i> +91-9999878398 </p>#}
                <p><i class="fa fa fa-envelope"></i> webmaster@vapemanager.com </p>


            </div>


            <div class=" col-sm-4 col-md  col-6 col">
                <h5 class="headin5_amrc col_white_amrc pt2">Quick links</h5>
                <!--headin5_amrc-->
                <ul class="footer_ul_amrc">
                    <li><a href="{% url 'alchemy:index' %}">Alchemy</a></li>
                    <li><a href="#{% url 'contact' %}">Contact us</a></li>
                    {#                    <li><a href="#">Hollow Man Montage</a></li>#}
                    {#                    <li><a href="#">Ebay & Amazon</a></li>#}
                    {#                    <li><a href="#">Hair Masking/Clipping</a></li>#}
                    {#                    <li><a href="#">Image Cropping</a></li>#}
                </ul>
                <!--footer_ul_amrc ends here-->
            </div>


            <div class=" col-sm-4 col-md  col-6 col">
                {#                <h5 class="headin5_amrc col_white_amrc pt2">Quick links</h5>#}
                {#                <!--headin5_amrc-->#}
                {#                <ul class="footer_ul_amrc">#}
                {#                    <li><a href="#">Remove Background</a></li>#}
                {#                    <li><a href="#">Shadows & Mirror Reflection</a></li>#}
                {#                    <li><a href="#">Logo Design</a></li>#}
                {#                    <li><a href="#">Vectorization</a></li>#}
                {#                    <li><a href="#">Hair Masking/Clipping</a></li>#}
                {#                    <li><a href="#">Image Cropping</a></li>#}
                {#                </ul>#}
                <!--footer_ul_amrc ends here-->
            </div>


            <div class=" col-sm-4 col-md  col-12 col">
                {#                <h5 class="headin5_amrc col_white_amrc pt2">Follow us</h5>#}
                {#                <!--headin5_amrc ends here-->#}
                {##}
                {#                <ul class="footer_ul2_amrc">#}
                {#                    <li><a href="#"><i class="fab fa-twitter fleft padding-right"></i> </a>#}
                {#                        <p>Lorem Ipsum is simply dummy text of the printing...<a href="#">https://www.lipsum.com/</a>#}
                {#                        </p></li>#}
                {#                    <li><a href="#"><i class="fab fa-twitter fleft padding-right"></i> </a>#}
                {#                        <p>Lorem Ipsum is simply dummy text of the printing...<a href="#">https://www.lipsum.com/</a>#}
                {#                        </p></li>#}
                {#                    <li><a href="#"><i class="fab fa-twitter fleft padding-right"></i> </a>#}
                {#                        <p>Lorem Ipsum is simply dummy text of the printing...<a href="#">https://www.lipsum.com/</a>#}
                {#                        </p></li>#}
                {#                </ul>#}
                <!--footer_ul2_amrc ends here-->
            </div>
        </div>
    </div>


    <div class="container">
        <ul class="foote_bottom_ul_amrc">
            <li><a href="#">Home</a></li>
            <li><a href="#">About</a></li>
            <li><a href="#">Services</a></li>
            <li><a href="#">Pricing</a></li>
            <li><a href="#">Blog</a></li>
            <li><a href="#">Contact</a></li>
        </ul>
        <!--foote_bottom_ul_amrc ends here-->
        <p class="text-center">Copyright @2017 | Designed With by <a href="#">Your Company Name</a></p>

        <ul class="social_footer_ul">
            <li><a href="#"><i class="fab fa-facebook-f"></i></a></li>
            <li><a href="#"><i class="fab fa-twitter"></i></a></li>
            <li><a href="#"><i class="fab fa-linkedin"></i></a></li>
            <li><a href="#"><i class="fab fa-instagram"></i></a></li>
        </ul>
        <!--social_footer_ul ends here-->
    </div>

</footer>

templates/home.html
<!-- templates/home.html -->
{% extends 'base.html' %}

{% block title %}Vape Manager{% endblock %}
{#{% block page_title %}Vape Manager{% endblock %}#}
<style>
    /* Make the image fully responsive */
    .carousel-inner img {
        width: 100%;
        height: 100%;
    }
</style>
{% block content_header %}
    <div id="demo" class="carousel slide" data-ride="carousel">

        <!-- Indicators -->
        <ul class="carousel-indicators">
            <li data-target="#demo" data-slide-to="0" class="active"></li>
            <li data-target="#demo" data-slide-to="1"></li>
            <li data-target="#demo" data-slide-to="2"></li>
        </ul>

        <!-- The slideshow -->
        <div class="carousel-inner">
            <div class="carousel-item active">
                <img src="https://dummyimage.com/1200x400/000/fff.png&text=Vape+Manager" alt="Los Angeles">
            </div>
            <div class="carousel-item">
                <img src="https://dummyimage.com/1200x400/000/fff.png&text=Alquimia" alt="Chicago">
            </div>
            <div class="carousel-item">
                <img src="https://dummyimage.com/1200x400/000/fff.png&text=Vape+Manager" alt="New York">
            </div>
        </div>

        <!-- Left and right controls -->
        <a class="carousel-control-prev" href="#demo" data-slide="prev">
            <span class="carousel-control-prev-icon"></span>
        </a>
        <a class="carousel-control-next" href="#demo" data-slide="next">
            <span class="carousel-control-next-icon"></span>
        </a>

    </div>

{% endblock %}
{% block content %}
    <h2>¡Bienvenidos a Vape Manager!</h2>
    <p>
        Vape Manager ha sido creada para ser una plataforma para la comunidad de vapeo.
        Su finalidad actual es ayudar a gestionar y compartir recetas de alquimia entre usuarios,
        así como facilitar la creación de recetas registrando las recetas creadas y anotando sus fallos.
    </p>
    <p>
        Se prevé extender su funcionalidad a otros campos de interés de los usuarios de cigarrillos electrónicos. Cómo
        una
        calculadora para encontrar la configuración óptima de los mods mecánicos (batería, resistencia, ...) y un foro
        para
        que los usuarios compartan su experiencia y se cree una comunidad consolidada.
    </p>

    <h3>Alquimia</h3>
    <p>
        La alquimia consiste en la elaboración de líquidos para vapear a partir de diferentes aromas y otros
        componentes.
        Los alquimistas mezclan los distintos componentes para crear un nuevo líquido para vapear.
    </p>
    <h4>Recetas</h4>
    <p>
        La definición de un líquido para un cigarrillo electrónico se describe en una receta, símil a la cocina.
        Esta formada por un listado de componentes y su proporción en la mezcla, llamados ingredientes.
    </p>
    <p>
        <b>¡Vape Manager le permitirá mantener un registro de sus recetas y compartir las mejores con la comunidad!</b>
    </p>
    <h4>Componentes</h4>
    <p>
        Los componentes básicos de los ingredientes de las recetas són:
    </p>
    <ul>
        <li><b>Aromas:</b></li>
        <li><b>Propilenglicol:</b></li>
        <li><b>Glicerina Vegetal:</b></li>
        <li><b>Moléculas:</b></li>
    </ul>
    <h4>Cómo fabricar tus líquidos</h4>
    <iframe width="420" height="315" src="https://www.youtube.com/embed/yXmrYL344P8"></iframe>
    {#https://www.steam-engine.org/juice.html#}
    <hr>
    {% if user.is_authenticated %}
        {% include 'home_logged.html' %}
    {% else %}
        <p>You are not logged in. </p>
        <p><b>Press next button to begin to use the platform:</b></p>
        <a class="btn btn-primary" href="{% url 'account_login' %}">login</a>
    {% endif %}
{% endblock %}

{% block content_footer %}
    <div class="jumbotron text-center" style="margin-bottom:0">
        {% if user.is_authenticated %}
            <p><a href="{% url 'account_logout' %}">logout</a></p>
            <p><a href="{% url 'account_reset_password' %}">reset password</a></p>
        {% else %}
            <a href="{% url 'account_login' %}">login</a>
        {% endif %}
    </div>
{% endblock %}

templates/home_logged.html
<div class="row">
    <div class="col-12">
        <h2>Welcolme to Vape Manager platform {{ user.username }}!</h2>
        <p>Select one of the next items to access to your app.</p>
    </div>
</div>
<div class="row">
    <div class="col-12">
        <div class="card-deck">
            {#    <div class="card mb-3" style="width: 18rem;">#}
            {#      <div class="card-header bg-success text-white">Recipes</div>#}
            {#      <div class="card-body">#}
            {#        <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>#}
            {#        <a href="{% url 'alchemy:recipes_list' %}" class="btn btn-success">Recipes list</a>#}
            {#      </div>#}
            {#    </div>#}
            <div class="card mb-3" style="width: 18rem;">
                <div class="card-header bg-warning text-white">Alchemy</div>
                <div class="card-body">
                    <p class="card-text">Access to the platform to manage your alchemy recipes</p>
                    <a href="{% url 'alchemy:index' %}" class="btn btn-warning">Alchemy manager</a>
                </div>
            </div>
            {#    <div class="card mb-3" style="width: 18rem;">#}
            {#      <div class="card-header bg-secondary text-white">Components</div>#}
            {#      <div class="card-body">#}
            {#        <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>#}
            {#        <a href="{% url 'alchemy:components_list' %}" class="btn btn-secondary">Components list</a>#}
            {#      </div>#}
            {#    </div>#}
        </div>
    </div>
</div>

templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-white" id="mainNav">
    <a class="navbar-brand" href="/">Vape Manager</a>
    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse"
            data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false"
            aria-label="Toggle navigation">
        Menu
        <i class="fa fa-bars"></i>
    </button>
    <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
            <li class="nav-item">
                <a class="nav-link " href="{% url 'contact' %}">Contact</a>
            </li>
            {% if request.user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link " href="{% url 'alchemy:index' %}">Alquimia</a>
                </li>
                <li class="nav-item">
                    <a href="{% url 'profile' %}">
                        <img src="{{ request.user.user_profile.image.url_60x60 }}" style="height:40px;"
                             alt="{{ request.user.username }}" class="avatar rounded-circle">
                    </a>
                </li>

                <li class="nav-item">
                    <a class="nav-link " href="{% url 'account_logout' %}">Logout</a>
                </li>
            {% else %}

                <li class="nav-item">
                    <a class="nav-link " href="{% url 'account_login' %}">Login</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link " href="{% url 'account_signup' %}">Signup</a>
                </li>
            {% endif %}

        </ul>
    </div>
</nav>

templates/signup.html
<!-- templates/signup.html -->
{% extends 'base.html' %}

{% block title %}Sign Up{% endblock %}

{% block content %}
    <h2>Sign up</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Sign up</button>
    </form>
{% endblock %}